var GAME_LEVELS = [
  ["  x           vvv                                                               ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x o                                                                           ",
   "  x          x      xx                                            xxx           ",
   "  x xx                      x                                    xx!xx          ",
   "  x                                                              x!v!x          ",
   "  x                                xxx                           xx=xx          ",
   "  x                                                               xvx           ",
   "  x                                                                         xx  ",
   "  x                                        xx                               |x  ",
   "  x                                                                          x  ",
   "  x         xx = xx                                                     o   |x  ",
   "  x        xxx   xxx                xx                                       x  ",
   "  x  @    xxxx o xxxx      w  x     xx                                      |x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxx               x     xxxxxxx   xxxxxxxxx  ",
   "                              x= =x  xx            w x= = =x                    ",
   "                              x= =xo     xx  xx  xx xx= = =x       x            ",
   "                              x= =x                  x= = =x                    ",
   "                              xxxxxx                 xxxxxxx                    ",
   "                                                                                ",
   "                                      x                                         ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                 ",
   "x          |         |        x!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "x             |               x!!!!!!!xxxxxxxxxxxx                         x    ",
   "x  @                          x!!!!!!!xxxxxxxx=                            x    ",
   "xxxxxxxx         |            x!!!!!!!xxxxxx=                              x    ",
   "       xxxxxxxxxxxxxxxx       x!!!!!!!xxx=                                 x    ",
   "                  |   !       xxx| xxxx=                                   x    ",
   " o                  o !                           xxxx  xxxxxx!!!xxxx  o   x    ",
   "xxxxx                 !xx                         xxxx  xx    v  v         x    ",
   "               xxxxxxx!                       xxxxxxxxxxxx             o   x    ",
   "            w  x|     !o          |           x                            x    ",
   "        xx     x      xxxxxxxxxxxxxxxxxxxxxxxxx   o                    o   x    ",
   "               x                         x                                 x    ",
   " w             x                     o o x                                 x    ",
   "              xx              xxxxxxxxxxxx                                 x    ",
   "               x   x                                                       x    ",
   "               x|  xx                            x                         x    ",
   "x         w    x   x    x x                                                x    ",
   "              xx   x                                                       x    ",
   "       x       x|  x                                                       x    ",
   "                   x                                  x                x   x    ",
   "x                  x     x                 xx                     xxx      x    ",
   "                   x                       |x                     xxx      x    ",
   "              xx   x  w                     x                     xxx!!!!!!x    ",
   "               x   x                      o x w        w xx       xxx!!!!!!x    ",
   "    xxxx       x| xx      x      x       xx xxxxxxxxxxxxxx        xxx!!!!!!x    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!x    ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "xxxxx                                                                           ",
   "x   x                                                                           ",
   "x @ x                                                                           ",
   "x   x                                                                           ",
   "x   x                   xx   x  xxxxxx                                          ",
   "x   x               xx!!!!!!!!!!!!!!!x                                          ",
   "x   x                 vvvvvvvvvvvvvvvx                                          ",
   "x   x                  v    v    v   x                                          ",
   "x   x                 v  v   v v  v  x                                          ",
   "x   x             x   v            v x                                          ",
   "x   x                 v    v   v     x                                          ",
   "x   x                   v           x                                           ",
   "x   x       xx        v  v   v   xxx                                            ",
   "x   xx                v  v     xx                                               ",
   "x   x            xx       v   x                                                 ",
   "x   x              x  v       x o                                               ",
   "x   x            o x  v  v v v xxxxxxx                                          ",
   "x   xx         x   x  v                                                         ",
   "x   x           xxx      v    v                                                 ",
   "x   x                 v        v                                                ",
   "x   x                     v  v                                                  ",
   "x   x    x            v   v                                                     ",
   "x   x                       v                                                   ",
   "x   x                 v  v     v                                                ",
   "x   x                 v      v                                                  ",
   "x   x         x            v                                                    ",
   "x   x                x   v       v                                              ",
   "x   x               xxv v      v                                                ",
   "x   x              xxxxx     v                                                  ",
   "x   x            xxxxxxxx v    v  v                                             ",
   "x              xxxxxxxxxxxx                                                     ",
   "x           xxxxxxxxxxxxxxxx v    v                                             ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!                             ",
   "                                                                                "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
